### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by grace00s** [Xib3rR4dAr/WannaRace#3]
hello, im a complete noob here.. i was trying to sudo docker run -it --rm xib3rr4dar/wanna_race:1.0
but i always get this error docker: Error response from daemon: pull access denied for xib3rr4dar/wanna_race, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
can you help please

**Comment by Xib3rR4dAr** [comment]
before running docker image, it must be built first.
As mentioned in the readme, build the Docker image with:
```bash
git clone https://github.com/Xib3rR4dAr/WannaRace && cd WannaRace
docker build -t xib3rr4dar/wanna_race:1.0 .
```

**Comment by grace00s** [comment]
Yh, I did all that before running it. I built the image with the Dockerfile which had some 13 steps to execute. Then I tried to run it.
I have even downloaded the zip file and set it up on my local machine, set up the database and all but when I click the unused vouchers there's no pop up or anything to show the vouchers (aaaaaaaaaaaab, aaaaaaaaaaaab etc), same with the current balance, login and reset. I really need to use your app but just seem not able to.

Can you consider hosting it on free platform like infinityfree for easy testing please..

**Comment by Xib3rR4dAr** [comment]
Can you post screenshots of docker image building and running?
What steps you followed to set it up on local machine?
Did you change credentials in config.php to match database credentials?
What happens when you click any button, is any popup displayed?

**Comment by grace00s** [comment]
![docker](https://user-images.githubusercontent.com/113814531/191703969-289bf122-4a62-4a11-b6c9-66012d6c4a20.png)
![docker0](https://user-images.githubusercontent.com/113814531/191704229-01d4fbcb-e4af-4563-93ec-e8483cf37c4a.png)
So this is the Dockerfile being built..

**Comment by grace00s** [comment]
![Race 1 2 3](https://user-images.githubusercontent.com/113814531/191704476-23daf995-c701-461e-b724-97c04e375840.png)
![database](https://user-images.githubusercontent.com/113814531/191704549-784474a3-a7fd-461c-b312-045523598f59.png)
So that's how it looks on my localhost.
For the database setup.
- I created a USER 'raceuser@localhost' IDENTIFIED BY 'Rac3R_we3'
- GRANT ALL PRIVILEGES
- FLUSH PRIVILEGES
- Then CREATE database db_race

Then I logged in with the credentials through phpmyadmin and imported database.sql in src directory

**Comment by grace00s** [comment]
But I get no pop up or anything when I click on unused vouchers, current balance, buy mega box.
I only get a pop up when I click on reset db prompting me whether I'm sure if I want to reset it "Are you sure you want to reset?". 

When I tried to recharge one of the vouchers say aaaaaaaaaaaab and capture the request with burp suite, I sent it to turbo intruder and got 404 page not found

**Comment by Xib3rR4dAr** [comment]
In screenshots, you have used command:
```bash
docker build .
```
instead of:
```bash
docker build -t xib3rr4dar/wanna_race:1.0 .
```
due to which tag is not assigned to built image.
Use following to build the image:
```bash
docker build -t xib3rr4dar/wanna_race:1.0 .
```
Previously you built images without a tag, you can use `docker ps` to view built images and then run them with:
```bash
# docker run -it --rm -p 9050:80 {IMAGE_ID_HERE}
```

**Comment by Xib3rR4dAr** [comment]
Can you share screenshots of 404 pages, browser console and network tab when you click any button?

**Comment by Xib3rR4dAr** [comment]
Webapp is setup at: [Wanna Race](http://wannarace.infinityfreeapp.com/)
(Infinity free app sometimes gets caching issues)

**Comment by grace00s** [comment]
![Screenshot from 2022-09-23 15-14-20](https://user-images.githubusercontent.com/113814531/191994861-2ca07ca0-3c73-4518-83be-828ace81cc68.png)
it worked like a charm, thanks very much for your patience i appreciate.. 
omalleygrace771@gmail.com is my email, i would to learn as much as i can from you so if you have any other challenges or you up some please let me know..... thanks again.

**Comment by grace00s** [comment]
i tried challenge #2, first i logged in and captured the request with burp, sent to turbo intruder to make concurrent request but it didn't wok. Then i use curl to make the request with two different cookies from different browsers and it worked..
![Screenshot from 2022-09-23 20-00-21](https://user-images.githubusercontent.com/113814531/192050378-5296032b-6255-4502-ad63-07c82db955a6.png)

let me know if its correct

**Comment by Xib3rR4dAr** [comment]
>i tried challenge # 2, first i logged in and captured the request with burp, sent to turbo intruder to make concurrent request but it didn't wok.

Yes, it wont work since PHP sessions are single threaded. ie if same PHPSESSID cookie is used in request, race condition won't be possible. Therefore different PHPSESSID cookie value is to be used to get race condition working.

**Solution for Challenge # 2**:
PHPSESSID cookie is generated in response to login request. Get multiple PHPSESSID cookie values by logging in multiple times.  
Then while trying race condition, PHPSESSID should be changed in every request ie:  
First request: Valid PHPSESSID 1 + First Voucher  
Second simultaneous Request: Valid PHPSESSID 2 + First Voucher  
Third simultaneous Request: Valid PHPSESSID 3 + First Voucher  
and so on.

**Comment by Xib3rR4dAr** [comment]
> let me know if its correct

It's not correct. By removing **PHPSESSID** named cookie, you solved challenge  # 1 instead of # 2.
Session cookie name is **PHPSESSID** instead of **session** which is generated after logging in. Since challenge # 2 is to be solved after logging in, therefore **PHPSESSID** cookie must be set in request while recharging from a voucher code.

**Comment by grace00s** [comment]
![Screenshot from 2022-09-26 13-05-14](https://user-images.githubusercontent.com/113814531/192284501-5f0da21f-bbea-4123-8c39-46d306412ef7.png)
i hope i got it correct this time...

i know this is off-topic but i was wondering if you know how to get a burpsuite pro license for free.. i tried to request for a trial key but i didn't get it and contacted their desk help but they said they only offer to businesses. i requested it with a .@proton.me..
i saw some guys on youtube working around this license key by generating some.. one of them github account is @SNGWN..
do you know anyway work around??

**Comment by Xib3rR4dAr** [comment]
Yes, that's the solution for Challenge # 2.
If you are a student, you can get Burp Suite professional trial for a month with your student email.
Hopefully, your issue with setting up/getting flag is answered, closing it.
